version: "3.8"
services:
  cryptobot-andreas:
    build: .
    environment:
      ACTIVE_CONFIG: ANDREAS
      MONGODB_URL: mongodb://db_admin:qrXp0HtVfWDH1otKSZM9HiC8m838Ud5u@mongo:27017/cryptobot?authSource=admin
    volumes:
      - ./logs:/app/logs
    networks:
      - shared

  cryptobot-jonas:
    build: .
    environment:
      ACTIVE_CONFIG: JONAS
      MONGODB_URL: mongodb://db_admin:qrXp0HtVfWDH1otKSZM9HiC8m838Ud5u@mongo:27017/cryptobot?authSource=admin
    volumes:
      - ./logs:/app/logs
    networks:
      - shared

  cryptobot-joren:
    build: .
    environment:
      ACTIVE_CONFIG: JOREN
      MONGODB_URL: mongodb://db_admin:qrXp0HtVfWDH1otKSZM9HiC8m838Ud5u@mongo:27017/cryptobot?authSource=admin
    volumes:
      - ./logs:/app/logs
    networks:
      - shared

  cryptobot-yente:
    build: .
    environment:
      ACTIVE_CONFIG: YENTE
      MONGODB_URL: mongodb://db_admin:qrXp0HtVfWDH1otKSZM9HiC8m838Ud5u@mongo:27017/cryptobot?authSource=admin
    volumes:
      - ./logs:/app/logs
    networks:
      - shared

networks:
  shared:
    name: shared
    driver: bridge
