version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
        MONGO_INITDB_ROOT_USERNAME: db_admin
        MONGO_INITDB_ROOT_PASSWORD: qrXp0HtVfWDH1otKSZM9HiC8m838Ud5u
    ports:
      - 27017:27017
    networks:
      - shared
    volumes:
      - /var/mongodb:/data/db

networks:
  shared:
    name: shared
    driver: bridge
