info = client.get_exchange_info()
symbol_info = client.get_symbol_info('BNBUSDT')
depth = client.get_order_book(symbol='BNBUSDT')
avg_price = client.get_avg_price(symbol='BNBUSDT')
tickers = client.get_ticker()
account_info = client.get_account()
balance = client.get_asset_balance(asset='USDT')
bnb = client.get_asset_balance(asset='BNB')
trades = client.get_my_trades(symbol='BNBUSDT')
print(f"Je hebt {balance['free']} USDT en {bnb['free']} BNB")