version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
        MONGO_INITDB_ROOT_USERNAME: db_admin
        MONGO_INITDB_ROOT_PASSWORD: qrXp0HtVfWDH1otKSZM9HiC8m838Ud5u
    ports:
      - 27017:27017
    networks:
      - shared
    volumes:
      - /var/mongodb:/data/db
  
  questdb:
    image: questdb/questdb
    container_name: questdb
    restart: unless-stopped
    ports:
      - 9000:9000 # REST API and Web Console
      - 9003:9003 # Min health server
      - 9009:9009 # InfluxDB line protocol
      - 8812:8812 # Postgres wire protocol
    networks:
      - shared
    volumes:
      - /var/questdb:/root/.questdb/db

networks:
  shared:
    name: shared
    driver: bridge
