version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: unless-stopped
    environment:
        MONGO_INITDB_ROOT_USERNAME: db_admin
        MONGO_INITDB_ROOT_PASSWORD: qrXp0HtVfWDH1otKSZM9HiC8m838Ud5u
    ports:
      - 27017:27017
    networks:
      - shared
    volumes:
      - /var/mongodb:/data/db

  influxdb:
      image: influxdb:alpine
      container_name: influxdb
      restart: unless-stopped
      environment:
          DOCKER_INFLUXDB_INIT_USERNAME: db_admin
          DOCKER_INFLUXDB_INIT_PASSWORD: qrXp0HtVfWDH1otKSZM9HiC8m838Ud5u
          DOCKER_INFLUXDB_INIT_ORG: crypto
          DOCKER_INFLUXDB_INIT_BUCKET: orders
          DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: m0DQvW6wvIdy0l2YN3dceFKR4LInurm4-yhoR5r0Uq95F-btt21K0GmFeZORbujdSwJ0iqosr5dHlhr-ghc9tA==
      ports:
          - 8086:8086
      networks:
          - shared
      volumes:
          - /var/influxdb:/var/lib/influxdb2

networks:
  shared:
    name: shared
    driver: bridge
