version: "3.5"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
        MONGO_INITDB_ROOT_USERNAME: db_admin
        MONGO_INITDB_ROOT_PASSWORD: qrXp0HtVfWDH1otKSZM9HiC8m838Ud5u
    ports:
      - 27017:27017
    networks:
      - shared
    volumes:
      - /var/mongodb:/data/db
      
  influxdb:
      image: influxdb:latest
      container_name: influxdb
      restart: unless-stopped
      environment:
          DOCKER_INFLUXDB_INIT_USERNAME: db_admin
          DOCKER_INFLUXDB_INIT_PASSWORD: qrXp0HtVfWDH1otKSZM9HiC8m838Ud5u
          DOCKER_INFLUXDB_INIT_ORG: crypto
          DOCKER_INFLUXDB_INIT_BUCKET: orders
      ports:
          - 8086:8086
      networks:
          - shared
      volumes:
          - /var/influxdb:/data/db

networks:
  shared:
    name: shared
    driver: bridge
