version: "3.1"

services:
  mongo:
    image: mongo
    restart: unless-stopped
    environment:
        MONGO_INITDB_ROOT_USERNAME: db_admin
        MONGO_INITDB_ROOT_PASSWORD: qrXp0HtVfWDH1otKSZM9HiC8m838Ud5u
    ports:
      - 27017:27017
    volumes:
      - /var/mongodb:/data/db
    networks:
      - shared

networks:
    shared:
      driver: bridge
